### PR TITLE
Better log output to console

### PR DESCRIPTION
**Pull request by chipironcin**
Help to discern what is the regular expression and where is it looking for in the console output.

### CODE REVIEW

**Comment by chipironcin** [comment]
Currently, the regexp I want to check is `Final result: UNSTABLE`. Then:
```
Checking Final result: UNSTABLE
```
But the above might be confusing as it is not clear what is the regular expresion.
I propose changing it to:
```
Checking for 'Final result: UNSTABLE' in /home/user/ws/xxx/logs/*
```

**Comment by chipironcin** [comment]
Any admin around here?

**Comment by basil** [comment]
I recently started maintaining this plugin and am starting to go through the PR backlog. This change looks good overall! There is only one more thing I'd like to see before merging this PR: rebasing the PR against the latest code in master and getting the newly-added tests (from #12) to pass against this change. The current change will break the tests, as the tests depend on the current console log format. It should be trivial to update the tests to work with the new console log format from this change. Once the code is rebased and the tests are updated with the new console log format, I'll be happy to merge this!

**Comment by chipironcin** [comment]
Will do soon. Thanks @basil

**Comment by chipironcin** [comment]
I performed the changes in the master branch of my repository which lead to some technical issues.
Dismissing this PR in favor of https://github.com/jenkinsci/text-finder-plugin/pull/17

**Pull request closed without merging**
