### PR TITLE
Better log output to console

### PR DESCRIPTION
**Pull request by chipironcin**
This change improves what the plugin logs to the console to it is easier for the user to identify what the plugin is looking for and where.

Updated the tests

### CODE REVIEW

**Comment by chipironcin** [comment]
@basil 
What is the best way of launching the tests for this locally?
Can you re run tests in Jenkins? I cannot tell from the logs if they are failing because of my changes or because something else.

**Comment by basil** [comment]
Looks like your automated test run had an infrastructure-related issue in the `windows-2.121.1` branch, which then caused the other branches to be interrupted before the tests could run. I surmise this failure wouldn't happen if you ran the tests again a bit later. If it does, I can investigate further and possibly file an INFRA bug.

To run the tests locally, you can use `mvn clean install` (which is essentially what the CI system does). You can also run the tests from within IntelliJ or any other IDE with a JUnit runner.

**Comment by chipironcin** [comment]
It passes locally for me:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running InjectedTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.521 s - in InjectedTest
[INFO] Running hudson.plugins.textfinder.TextFinderPublisherAgentTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.295 s - in hudson.plugins.textfinder.TextFinderPublisherAgentTest
[INFO] Running hudson.plugins.textfinder.TextFinderPublisherFreestyleTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.705 s - in hudson.plugins.textfinder.TextFinderPublisherFreestyleTest
[INFO] Running hudson.plugins.textfinder.TextFinderPublisherPipelineTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.213 s - in hudson.plugins.textfinder.TextFinderPublisherPipelineTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 22, Failures: 0, Errors: 0, Skipped: 0
```

Can we rerun?

**Comment by basil** [comment]
I merged this change after seeing that the tests passed locally for you, but once I did so the build started failing. Therefore, I've reverted the change. Can you please rebase against the latest `master` branch and submit a new pull request? Then we can work on getting the build working and the tests passing.

**Comment by chipironcin** [comment]
https://github.com/jenkinsci/text-finder-plugin/pull/21

**Pull request merged**
