### PR TITLE
Add support for Jenkins pipeline support

### PR DESCRIPTION
**Pull request by jwillemsen**
Attempt to add support for Jenkins pipeline support.

### CODE REVIEW

**Comment by jwillemsen** [comment]
Looks the checks are more strict than in the past, pull request check fails due to other files as far as I can tell

**Comment by jwillemsen** [comment]
Will keep the remark for the commit message in mind for future commits

**Comment by tuvoksg1** [comment]
Any update on this pull request? It is badly needed for our pipeline build

**Comment by jwillemsen** [comment]
When you are using pipeline you can use the logContains() functionality, like:
```
  if(manager.logContains("\\[Autobuild Unstable\\]")) {
    manager.buildUnstable()
  }
```

**Comment by MarkEWaite** [comment]
I think the groovy post build plugin better covers this need,  as noted by
Johnny.  The manager. LogContains syntax has been enough for my need.

**Comment by tuvoksg1** [comment]
Hi guys, thanks for the feedback.
I'm trying to use the contains(file, regexp) function of post build plugin.
So far I'm getting the error "EchoStep.message expects class java.lang.String but received class org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException".

From the documentation on the plugin site, the contains function is not whitelisted and thus needs admin approval. However when I go to Manage Jenkins > Script Approval, I don't see anything pending approval.

Any ideas how this function is meant to be used?

**Comment by MarkEWaite** [comment]
Can you explain why you're using contains rather than logContains?

I believe the groovy code in the pipeline executes on the master.  Requesting contains(file) will require that file exist on the master, even if your job ran on an agent that is not the agent.

I think it may be easier to echo (or cat) the contents of the file you're trying to read into the build log, then use logContains() to read from the log.

**Comment by maultosar** [comment]
Hey! Will text finder ever be implemented? We have a need to parse Junit results without contamination of Jenkins log with test results' content:)

**Comment by Jochen-A-Fuerbacher** [comment]
There's no need to increase parent version to 2.17, add workflow dependencies or `DataBoundSetter` instead of `DataBoundConstructor`.

I just opened an other pull request, adding pipeline support in #10.

**Comment by MarkEWaite** [comment]
I propose this pull request be closed in favor of #12

**Pull request closed without merging**
